In [1]:
import pandas as pd

df = pd.read_csv('./TDHospital/TD_HOSPITAL_TRAIN.csv')
df

,timeknown,cost,reflex,sex,blood,bloodchem1,bloodchem2,temperature,race,heart,...,diabetes,income,extraprimary,bloodchem6,education,psych5,psych6,information,cancer,death
0,4.0,3008.38867,11.228005,male,20.699219,2.199707,1.299805,35.59375,white,103.0,...,0.0,$11-$25k,COPD/CHF/Cirrhosis,167.5000,20.0,30.0,2.000000,0.0,no,1.0
1,467.0,23585.89060,9.714861,M,9.398438,NaN,0.699951,39.00000,white,50.0,...,0.0,>$50k,Cancer,480.0000,16.0,11.5,1.000000,10.0,metastatic,1.0
2,533.0,4046.45898,11.353296,Male,19.296875,NaN,1.599854,38.19531,white,50.0,...,1.0,under $11k,ARF/MOSF,177.1250,5.0,18.0,0.000000,5.0,yes,0.0
3,68.0,NaN,9.269058,female,7.500000,2.500000,0.599976,37.59375,white,80.0,...,0.0,$11-$25k,COPD/CHF/Cirrhosis,NaN,12.0,7.0,1.839000,12.0,no,1.0
4,1605.0,6457.70703,8.655387,female,15.099609,4.399414,0.699951,35.69531,white,114.0,...,0.0,under $11k,COPD/CHF/Cirrhosis,233.3125,2.0,7.0,6.000000,12.0,no,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7053,841.0,18825.79690,10.897551,female,15.099609,NaN,0.899902,38.00000,black,150.0,...,0.0,$25-$50k,Coma,371.3750,17.0,17.0,5.000000,11.0,no,0.0
7054,258.0,68911.87500,10.325173,male,7.500000,3.199707,0.899902,37.59375,white,112.0,...,0.0,>$50k,ARF/MOSF,122.4375,20.0,24.5,0.000000,48.0,metastatic,1.0
7055,1325.0,15684.64840,9.838906,female,35.000000,2.799805,0.599976,36.59375,white,126.0,...,0.0,under $11k,COPD/CHF/Cirrhosis,240.0000,NaN,32.5,0.000000,11.0,no,0.0
7056,4.0,NaN,9.141439,1,18.199219,3.000000,0.899902,39.29688,white,132.0,...,0.0,NaN,Coma,228.0000,NaN,32.0,2.317871,3.0,yes,1.0
7057,14.0,5133.14844,11.006892,female,12.599609,2.299805,0.699951,38.50000,white,114.0,...,0.0,under $11k,COPD/CHF/Cirrhosis,NaN,12.0,8.0,5.000000,7.0,no,1.0

In [5]:
df.columns

Index(['timeknown', 'cost', 'reflex', 'sex', 'blood', 'bloodchem1',
       'bloodchem2', 'temperature', 'race', 'heart', 'psych1', 'glucose',
       'psych2', 'dose', 'psych3', 'bp', 'bloodchem3', 'confidence',
       'bloodchem4', 'comorbidity', 'totalcost', 'breathing', 'age', 'sleep',
       'dnr', 'bloodchem5', 'pdeath', 'meals', 'pain', 'primary', 'psych4',
       'disability', 'administratorcost', 'urine', 'diabetes', 'income',
       'extraprimary', 'bloodchem6', 'education', 'psych5', 'psych6',
       'information', 'cancer', 'death'],
      dtype='object')

In [6]:
null_counts = df.isnull().sum()
null_counts_dict = null_counts.to_dict()

null_counts_dict

{'timeknown': 0,
 'cost': 2705,
 'reflex': 0,
 'sex': 0,
 'blood': 161,
 'bloodchem1': 2591,
 'bloodchem2': 44,
 'temperature': 0,
 'race': 32,
 'heart': 0,
 'psych1': 0,
 'glucose': 3525,
 'psych2': 2245,
 'dose': 0,
 'psych3': 0,
 'bp': 0,
 'bloodchem3': 2012,
 'confidence': 166,
 'bloodchem4': 3403,
 'comorbidity': 0,
 'totalcost': 687,
 'breathing': 0,
 'age': 0,
 'sleep': 1792,
 'dnr': 26,
 'bloodchem5': 1749,
 'pdeath': 7058,
 'meals': 0,
 'pain': 0,
 'primary': 0,
 'psych4': 4334,
 'disability': 1102,
 'administratorcost': 139,
 'urine': 3794,
 'diabetes': 0,
 'income': 2275,
 'extraprimary': 0,
 'bloodchem6': 1793,
 'education': 1219,
 'psych5': 60,
 'psych6': 0,
 'information': 24,
 'cancer': 0,
 'death': 0}

In [8]:
sorted_null_counts = dict(sorted(null_counts_dict.items(), key=lambda item: item[1], reverse=True))

sorted_column_names = list(sorted_null_counts.keys())

sorted_null_counts

# looks like we can delete the following columns for sure:
# pdeath
# psych4
# urine
# glucose
# bloodchem4

{'pdeath': 7058,
 'psych4': 4334,
 'urine': 3794,
 'glucose': 3525,
 'bloodchem4': 3403,
 'cost': 2705,
 'bloodchem1': 2591,
 'income': 2275,
 'psych2': 2245,
 'bloodchem3': 2012,
 'bloodchem6': 1793,
 'sleep': 1792,
 'bloodchem5': 1749,
 'education': 1219,
 'disability': 1102,
 'totalcost': 687,
 'confidence': 166,
 'blood': 161,
 'administratorcost': 139,
 'psych5': 60,
 'bloodchem2': 44,
 'race': 32,
 'dnr': 26,
 'information': 24,
 'timeknown': 0,
 'reflex': 0,
 'sex': 0,
 'temperature': 0,
 'heart': 0,
 'psych1': 0,
 'dose': 0,
 'psych3': 0,
 'bp': 0,
 'comorbidity': 0,
 'breathing': 0,
 'age': 0,
 'meals': 0,
 'pain': 0,
 'primary': 0,
 'diabetes': 0,
 'extraprimary': 0,
 'psych6': 0,
 'cancer': 0,
 'death': 0}

In [9]:
sex_column = df['sex']

unique_sex_values = set()

for value in sex_column:
    unique_sex_values.add(value)

print(unique_sex_values)

{'1', 'female', 'M', 'Male', 'male'}

In [12]:
df = df[df['sex'] != '1']

df['sex'].replace({'female': '1', 'M': '0', 'Male': '0', 'male': '0'}, inplace=True)

df['sex'] = df['sex'].astype(int)
df

,timeknown,cost,reflex,sex,blood,bloodchem1,bloodchem2,temperature,race,heart,...,diabetes,income,extraprimary,bloodchem6,education,psych5,psych6,information,cancer,death
0,4.0,3008.38867,11.228005,0,20.699219,2.199707,1.299805,35.59375,white,103.0,...,0.0,$11-$25k,COPD/CHF/Cirrhosis,167.5000,20.0,30.0,2.000,0.0,no,1.0
1,467.0,23585.89060,9.714861,0,9.398438,NaN,0.699951,39.00000,white,50.0,...,0.0,>$50k,Cancer,480.0000,16.0,11.5,1.000,10.0,metastatic,1.0
2,533.0,4046.45898,11.353296,0,19.296875,NaN,1.599854,38.19531,white,50.0,...,1.0,under $11k,ARF/MOSF,177.1250,5.0,18.0,0.000,5.0,yes,0.0
3,68.0,NaN,9.269058,1,7.500000,2.500000,0.599976,37.59375,white,80.0,...,0.0,$11-$25k,COPD/CHF/Cirrhosis,NaN,12.0,7.0,1.839,12.0,no,1.0
4,1605.0,6457.70703,8.655387,1,15.099609,4.399414,0.699951,35.69531,white,114.0,...,0.0,under $11k,COPD/CHF/Cirrhosis,233.3125,2.0,7.0,6.000,12.0,no,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7051,421.0,NaN,9.350148,0,7.799805,NaN,0.699951,36.59375,white,74.0,...,0.0,NaN,Cancer,NaN,7.0,10.0,0.000,12.0,metastatic,1.0
7053,841.0,18825.79690,10.897551,1,15.099609,NaN,0.899902,38.00000,black,150.0,...,0.0,$25-$50k,Coma,371.3750,17.0,17.0,5.000,11.0,no,0.0
7054,258.0,68911.87500,10.325173,0,7.500000,3.199707,0.899902,37.59375,white,112.0,...,0.0,>$50k,ARF/MOSF,122.4375,20.0,24.5,0.000,48.0,metastatic,1.0
7055,1325.0,15684.64840,9.838906,1,35.000000,2.799805,0.599976,36.59375,white,126.0,...,0.0,under $11k,COPD/CHF/Cirrhosis,240.0000,NaN,32.5,0.000,11.0,no,0.0
7057,14.0,5133.14844,11.006892,1,12.599609,2.299805,0.699951,38.50000,white,114.0,...,0.0,under $11k,COPD/CHF/Cirrhosis,NaN,12.0,8.0,5.000,7.0,no,1.0